spring:
  application:
    name: spring boot 4 personal feature snippet
  profiles:
    active: local
  threads:
    virtual:
      enabled: true

springdoc:
  swagger-ui:
    path: /api-ui
    try-it-out-enabled: true
    filter: true
    operations-sorter: alpha
    tags-sorter: alpha
    syntax-highlight:
      theme: monokai
  api-docs:
    path: /api-docs
  show-actuator: true

logging:
  level:
    root: INFO
    org.spring.springframework.web: DEBUG
    com.application: DEBUG
    org.hibernate: ERROR
  pattern:
    console: "%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS Z}}){magenta} |  %clr(${LOG_LEVEL_PATTERN:%-5p}) | %clr(%-40.40logger{39}){cyan} | %clr(%-25.25M){yellow} | %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
